/**
 * models/SustainabilityInsight.js
 *
 * Stores one AI-generated sustainability insight per ESP device per day.
 * Generated by the Gemini daily cron (sustainabilityInsightService).
 */

const mongoose = require('mongoose');

const SustainabilityInsightSchema = new mongoose.Schema(
  {
    esp_id: {
      type: String,
      required: true,
      index: true,
      uppercase: true,
      trim: true,
    },
    // Calendar date (UTC midnight) this insight was generated for
    date: {
      type: Date,
      required: true,
      index: true,
    },
    // AI-generated sustainability recommendation
    insight: {
      type: String,
      required: true,
    },
    // Carbon emission data at time of generation
    dailyKWh: { type: Number, default: 0 },
    dailyCO2: { type: Number, default: 0 },
    monthlyKWh: { type: Number, default: 0 },
    monthlyCO2: { type: Number, default: 0 },
    sustainabilityScore: { type: Number, default: 0 },
  },
  {
    timestamps: true,
  }
);

// One insight per device per day
SustainabilityInsightSchema.index({ esp_id: 1, date: -1 });

module.exports = mongoose.model('SustainabilityInsight', SustainabilityInsightSchema);
